name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: "Unit Test"
    uses: na4ma4/actions/.github/workflows/unit-test.yml@main
    secrets: inherit
